protected (copy)/models/User.php
<?php

/**
 * This is the model class for table "users".
 *
 * The followings are the available columns in table 'users':
 * @property string $id
 * @property string $password
 * @property string $username
 */
class User extends CActiveRecord
{
	public $password1;
	public $password2;
	public $password3;
	/**
	 * Returns the static model of the specified AR class.
	 * @return Users the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'users';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('name,email,password', 'length', 'max'=>50),
			array('email','email'),
			array('department_id', 'numerical', 'integerOnly'=>true),
			
			array('username','unique'),
			array('username', 'length', 'min'=>2, 'max'=>20),
			array('name,username','required'),
			// The following rule is used by search().
			// Please remove those attributes that should not be searched.
			array('id, name, username', 'safe', 'on'=>'search'),
			array('password1,password2,password3','length','max'=>20),
			array('password1', 'compare', 'compareAttribute'=>'password2','message'=>'Passwords must be identical'),
			//array('password2', 'compare', 'compareAttribute'=>'password1','message'=>'Passwords must be identical'),
			array('password3', 'checkPassword','on'=>'changePassword'),
			array('password1,password2,password3','required','on'=>'changePassword'),
		);
	}

	public function checkPassword($attribute,$params)
	{
		$user=User::model()->find('username=?',array(Yii::app()->user->name));
		if ($user->password != md5($this->password3))
			$this->addError($attribute,'Password is incorrect.');
	}
	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'groups' => array(self::MANY_MANY, 'Groups', 'user_group(user_id, group_id)'),
			'department'=>array(self::BELONGS_TO, 'Department', 'department_id','joinType'=>'INNER JOIN'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'Id',
			'password' => 'Password',
			'username' => 'Username',
			'email' => 'Email',
			'password1' => 'Password',
			'password2' => 'Confirm&nbsp;Password',
			'password3' => 'Current&nbsp;Password',
			'department_id'=>'Department',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
	 */
	public function search()
	{
		// Warning: Please modify the following code to remove attributes that
		// should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id,false);

		$criteria->compare('username',$this->username,true);
		$criteria->compare('name',$this->name,true);
		return new CActiveDataProvider('User', array(
			'criteria'=>$criteria,
		));
	}
	
	public function validatePassword($password)
	{
		return md5($password)===$this->password;
	}
	public function behaviors(){
          return array( 'CAdvancedArBehavior' => array('class' => 'application.extensions.CAdvancedArBehavior'),
          	'ActiveRecordLogableBehavior'=>array('class'=>'application.behaviors.ActiveRecordLogableBehavior')
          );
   }
}

protected (copy)/controllers/UserController.php
<?php

class UserController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @var CActiveRecord the currently loaded data model instance.
	 */
	private $_model;

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			
			array('allow', 
				'users'=>array('@'),
				'expression'=>'Yii::app()->user->getPermission("users")',
			),
			
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 */
	public function actionView()
	{
		$this->render('view',array(
			'model'=>$this->loadModel(),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new User;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['User']))
		{
			if(isset($_POST['User']['Groups'])){
				$my_groups=$_POST['User']['Groups'];
				$model->groups=$my_groups;
			}
			$model->attributes=$_POST['User'];
			
			$model->password=md5($model->password1);
			if($model->save())
				$this->redirect(array('admin'));
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionUpdate()
	{
		$model=$this->loadModel();

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);
		
		if(isset($_POST['User']))
		{
			if(isset($_POST['User']['Groups'])){
				$my_groups=$_POST['User']['Groups'];
				$model->groups=$my_groups;
			}
			$model->attributes=$_POST['User'];
			if(!empty($model->password1))
				$model->password=md5($model->password1);
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}
	
	public function actionChangePassword()
	{
		$model=User::model()->find('LOWER(username)=?',array(strtolower(Yii::app()->user->name)));

		if(isset($_POST['User']))
		{
			
			$model->attributes=$_POST['User'];
			if(!empty($model->password1))
				$model->password=md5($model->password1);
				
			$model->setScenario('changePassword');
			if($model->save())
				$this->redirect(Yii::app()->homeUrl);
		}

		$this->render('changePassword',array(
			'model'=>$model,
		));
	}
	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'index' page.
	 */
	public function actionDelete()
	{
		if(Yii::app()->request->isPostRequest)
		{
			// we only allow deletion via POST request
			$model=$this->loadModel();
			$model->delete();

			// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
			if(!isset($_GET['ajax']))
				$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
		}
		else
			throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('User');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new User('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['User']))
			$model->attributes=$_GET['User'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 */
	public function loadModel()
	{
		if($this->_model===null)
		{
			if(isset($_GET['id']))
				$this->_model=User::model()->findbyPk($_GET['id']);
			if($this->_model===null)
				throw new CHttpException(404,'The requested page does not exist.');
		}
		return $this->_model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param CModel the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='user-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected (copy)/views/user/_form.php
<div class='form wide'>

<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'user-form',
	'enableAjaxValidation'=>false,
)); ?>


	<?php echo $form->errorSummary($model); ?>
<?php $this->beginWidget('system.web.widgets.CClipWidget', array('id'=>'User Information')); ?>
	<div class="row">
		<?php echo $form->labelEx($model,'name'); ?>
		<?php echo $form->textField($model,'name',array('size'=>20,'maxlength'=>50)); ?>
		
	</div>
	<?php if (Yii::app()->controller->action->id == 'create'){?>
	<div class="row">
		<?php echo $form->labelEx($model,'username'); ?>
		<?php echo $form->textField($model,'username',array('size'=>20,'maxlength'=>50)); ?>
	</div>
	<?php }?>
	<div class="row">
		<?php echo $form->labelEx($model,'email'); ?>
		<?php echo $form->textField($model,'email',array('size'=>20,'maxlength'=>50)); ?>
	</div>
	<div class="row">
		<?php echo $form->labelEx($model,'department_id'); ?>
		<?php 
		$ms=Department::model()->findAll(array('condition'=>'id <> 0'));
		$mArray=array();
		$mArray['']='Select';
		foreach($ms as $m){
			$mArray[$m->id]=$m->name;
		}
		echo CHtml::dropDownList('User[department_id]',$model->department_id, $mArray); ?>
	</div>
	<div class="row">
		<?php echo $form->labelEx($model,'password1'); ?>
		<?php echo $form->passwordField($model,'password1',array('size'=>20,'maxlength'=>50)); ?>

	</div>
	<div class="row">
		<?php echo $form->labelEx($model,'password2'); ?>
		<?php echo $form->passwordField($model,'password2',array('size'=>20,'maxlength'=>50)); ?>
	
	</div>
<?php $this->endWidget(); ?> 
	
<?php $this->beginWidget('system.web.widgets.CClipWidget', array('id'=>'Groups')); ?>
  <?php 
	$this->widget('application.components.Relation', array(
		'idValue'=>$model->id,
   		'model' => 'User',
   		'relation' => 'groups',
		'field'=>'id',
   		'fields' => 'name',
		'style' => 'Checkbox',
		'relatedPk'=>'id',
		'htmlOptions'=>array('template'=>'{input}{label}','separator'=>'<BR/>'),
		'manyManyTable' =>'user_group',
		'manyManyTableLeft' =>'user_id',
		'manyManyTableRight' =>'group_id',
		'returnLink' => 'none',
		'showAddButton' =>false,
		)
	); 
	?>
<?php $this->endWidget(); ?> 

<?php
$tabParameters = array();
foreach($this->clips as $key=>$clip)
    $tabParameters['tab'.(count($tabParameters)+1)] = array('title'=>$key, 'content'=>$clip);
?>
 
<?php $this->widget('system.web.widgets.CTabView', array('tabs'=>$tabParameters)); ?>

<div class="row buttons">
		<?php echo CHtml::submitButton($model->isNewRecord ? 'Create' : 'Save'); ?>
</div>
<?php $this->endWidget(); ?>

</div><!-- form -->

protected (copy)/views/user/_search.php
<div class="wide form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<div class="row">
		<?php echo $form->label($model,'id'); ?>
		<?php echo $form->textField($model,'id',array('size'=>20,'maxlength'=>20)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'username'); ?>
		<?php echo $form->textField($model,'username',array('size'=>20,'maxlength'=>50)); ?>
	</div>
	<div class="row">
		<?php echo $form->label($model,'name'); ?>
		<?php echo $form->textField($model,'name',array('size'=>20,'maxlength'=>50)); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton('Search'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

protected (copy)/views/user/_view.php
<div class="view">

	<b><?php echo CHtml::encode($data->getAttributeLabel('id')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->id), array('view', 'id'=>$data->id)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('password')); ?>:</b>
	<?php echo CHtml::encode($data->password); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('username')); ?>:</b>
	<?php echo CHtml::encode($data->username); ?>
	<br />


</div>

protected (copy)/views/user/admin.php
<?php
$this->breadcrumbs=array(
	'Users'=>array('admin'),
	'Manage',
);

$this->menu=array(
	array('label'=>'List User', 'url'=>array('index')),
	array('label'=>'Create User', 'url'=>array('create')),
);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$.fn.yiiGridView.update('user-grid', {
		data: $(this).serialize()
	});
	return false;
});
");
?>

<h1>Manage Users</h1>


<div class="search-form">
<?php $this->renderPartial('_search',array(
	'model'=>$model,
)); ?>
</div><!-- search-form -->

<?php $this->widget('zii.widgets.grid.CGridView', array(
	'id'=>'user-grid',
	'dataProvider'=>$model->search(),
	'columns'=>array(
		'id',
		'username',
		'name',
		'email',
		array(
			'class'=>'CButtonColumn',
		),
	),
)); ?>
<?php echo CHtml::Button('New User',array('submit'=>Yii::app()->createUrl('user/create')));?>

protected (copy)/views/user/changePassword.php
<h1>Change password user <?php echo $model->username; ?></h1>

<div class='form wide'>

<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'user-form',
	'enableAjaxValidation'=>false,
)); ?>


	<?php echo $form->errorSummary($model); ?>
	<div class="row">
		<?php echo $form->labelEx($model,'password3'); ?>
		<?php echo $form->passwordField($model,'password3',array('size'=>20,'maxlength'=>50)); ?>

	</div>
	<div class="row">
		<?php echo $form->labelEx($model,'password1'); ?>
		<?php echo $form->passwordField($model,'password1',array('size'=>20,'maxlength'=>50)); ?>

	</div>
	<div class="row">
		<?php echo $form->labelEx($model,'password2'); ?>
		<?php echo $form->passwordField($model,'password2',array('size'=>20,'maxlength'=>50)); ?>
	
	</div>



<div class="row buttons">
		<?php echo CHtml::submitButton('Change Password'); ?>
</div>
<?php $this->endWidget(); ?>

</div><!-- form -->

protected (copy)/views/user/create.php
<?php
$this->breadcrumbs=array(
	'Users'=>array('index'),
	'Create',
);

$this->menu=array(
	array('label'=>'List User', 'url'=>array('index')),
	array('label'=>'Manage User', 'url'=>array('admin')),
);
?>

<h1>Create User</h1>

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>
<?php echo CHtml::Button('Cancel',array('submit'=>Yii::app()->controller->createUrl('admin')));?>

protected (copy)/views/user/index.php
<?php
$this->breadcrumbs=array(
	'Users',
);

$this->menu=array(
	array('label'=>'Create User', 'url'=>array('create')),
	array('label'=>'Manage User', 'url'=>array('admin')),
);
?>

<h1>Users</h1>

<?php $this->widget('zii.widgets.CListView', array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
)); ?>

protected (copy)/views/user/update.php
<h1>Update user <?php echo $model->username; ?></h1>

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>
<?php echo CHtml::Button('Cancel',array('submit'=>Yii::app()->controller->createUrl('admin')));?>
<?php echo CHtml::Button('New',array('submit'=>Yii::app()->controller->createUrl('create')));?>

protected (copy)/views/user/view.php
<h1>View User <?php echo $model->username; ?></h1>

<?php $this->widget('zii.widgets.CDetailView', array(
	'data'=>$model,
	'attributes'=>array(
		'id',
		'username',
		'name',
	),
)); ?>
Groups
<?php 
$html="<table width='600' class='detail-view'>";
$class='odd';
foreach ($model->groups as $group){
	$html.="<tr class='$class'><td>$group->name</td></tr>";
	if ($class=='odd')
		$class='even';
	else 
		$class='odd';
}
$html.="</table>";
echo $html;
?>
<?php echo CHtml::Button('Go to List',array('submit'=>Yii::app()->createUrl('user/admin')));?>
<?php echo CHtml::Button('New',array('submit'=>Yii::app()->controller->createUrl('create')));?>